### ISSUE TITLE
ブランチをきって開発する

### ISSUE THREAD

**Issue by materialofmouse** [Yuto5176/Rayt_cited#1]
`git branch dev`　今のブランチ(今回はmaster)からdevブランチを切る
`git checkout dev`　devブランチに移動する
`git checkout -b dev` 上の２つのコマンド同時にやってくれる

機能でブランチを切るんだけど、最低限devブランチを切って、動くようになった状態でmasterにマージ(devでの更新をmasterに加えること)をやるといいかも。

**Comment by Yuto5176** [comment]
完全に理解した
